- Topbar:
  - " ":
    label: ""
    href: {{PROXMOX_URL}}
    widget:
      type: proxmox
      fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
      url: {{PROXMOX_URL}}
      username: {{PROXMOX_USERNAME}}
      password: {{PROXMOX_SECRET}}

- Media:
  - TrueNAS:
    icon: truenas
    href: {{TRUENAS_URL}}
    description: NAS
    ping: {{TRUENAS_IP}}
    widget:
      type: truenas
      fields: ["load", "uptime", "alerts"]
      url: {{TRUENAS_URL}}
      username: {{TRUENAS_USERNAME}}
      password: {{TRUENAS_PASSWORD}}
      nasType: scale

- Networking:
  - PiHole:
    icon: pi-hole
    href: {{PIHOLE_URL}}
    description: Network-wide adblocker/custom DNS server.
    ping: {{PIHOLE_IP}}
    widget:
      type: pihole
      fields: ["queries", "blocked", "blocked_percent", "gravity"]
      url: {{PIHOLE_URL}}
      version: 6
      key: {{PIHOLE_PASSWORD}}
