- Topbar:
    - " ":
        label: ""
        href: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
        widget:
            type: proxmox
            fields: ["vms", "lxc", "resources.cpu", "resources.mem"]
            url: "{{HOMEPAGE_VAR_PROXMOX_URL}}"
            username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
            password: "{{HOMEPAGE_VAR_PROXMOX_SECRET}}"

- Media:
    - TrueNAS:
        icon: truenas
        href: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
        description: NAS
        ping: "{{HOMEPAGE_VAR_TRUENAS_IP}}"
        widget:
            type: truenas
            fields: ["load", "uptime", "alerts"]
            url: "{{HOMEPAGE_VAR_TRUENAS_URL}}"
            username: "{{HOMEPAGE_VAR_TRUENAS_USERNAME}}"
            password: "{{HOMEPAGE_VAR_TRUENAS_PASSWORD}}"
            nasType: scale

- Networking:
    - PiHole:
        icon: pi-hole
        href: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
        description: Network-wide adblocker/custom DNS server.
        ping: "{{HOMEPAGE_VAR_PIHOLE_IP}}"
        widget:
            type: pihole
            fields: ["queries", "blocked", "blocked_percent", "gravity"]
            url: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
            version: 6
            key: "{{HOMEPAGE_VAR_PIHOLE_PASSWORD}}"
