networks:
  homelabnetwork:
    external: true

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    # user: ${PUID}:${PGID} # This container requires joining another containers network
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent:/config
      - /mnt/nas:/mnt/nas
      - /etc/localtime:/etc/localtime:ro
    network_mode: container:gluetun
    healthcheck:
      test: sh -c "ping -c1 8.8.8.8 >/dev/null 2>&1 && nslookup www.google.com >/dev/null 2>&1 && curl -s http://localhost:8080 || exit 1"
      interval: 20s
      timeout: 10s
      retries: 5
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    # user: ${PUID}:${PGID} # This container requires joining another containers network
    environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./nzbget:/config
      - /mnt/nas:/mnt/nas
      - /etc/localtime:/etc/localtime:ro
    network_mode: container:gluetun
    healthcheck:
      test: sh -c "ping -c1 8.8.8.8 >/dev/null 2>&1 && nslookup www.google.com >/dev/null 2>&1 && curl -s http://localhost:6789 || exit 1"
      interval: 20s
      timeout: 10s
      retries: 5
    labels:
      - deunhealth.restart.on.unhealthy=true 
    restart: unless-stopped

  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    user: ${PUID}:${PGID}   
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - STATE_DIR=/config
      - DOWNLOAD_DIR=/downloads
      - CREATE_CUSTOM_DIRS=false # Stops metube from re-creating the download directories with wrong permissions
      - CHOWN_DIRS=false # Stop metube from changing permissions of download directories
    ports:
      - 8081:8081
    volumes:
      - ./metube:/config
      - /mnt/nas:/mnt/nas
      - /mnt/nas:/downloads # Temporary, you should really change the directory in metube when dowloading
      - /etc/localtime:/etc/localtime:ro
    networks:
      homelabnetwork:
        ipv4_address: 172.39.0.20
    healthcheck:
      test: curl -s http://localhost:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped
