networks:
  homelabnetwork:
    external: true

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    # user: ${PUID}:${PGID} # This container requires joining another containers network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./prowlarr:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: container:gluetun
    healthcheck:
      test: sh -c "ping -c1 8.8.8.8 >/dev/null 2>&1 && nslookup www.google.com >/dev/null 2>&1 && curl -s http://localhost:9696 || exit 1"
      interval: 20s
      timeout: 10s
      retries: 5
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    # user: ${PUID}:${PGID} # linuxserver containers handle this with environment PUID, PGID
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./sonarr:/config
      - /mnt/nas:/mnt/nas
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
    networks:
      homelabnetwork:
        ipv4_address: 172.39.0.30
    healthcheck:
      test: curl -s http://localhost:8989 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - deunhealth.restart.on.unhealthy=true 
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    # user: ${PUID}:${PGID} # linuxserver containers handle this with environment PUID, PGID
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./radarr:/config
      - /mnt/nas:/mnt/nas
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7878:7878
    networks:
      homelabnetwork:
        ipv4_address: 172.39.0.31
    healthcheck:
      test: curl -s http://localhost:7878 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped

  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    # user: ${PUID}:${PGID} # linuxserver containers handle this with environment PUID, PGID
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./lidarr:/config
      - /mnt/nas:/mnt/nas
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8686:8686
    networks:
      homelabnetwork:
        ipv4_address: 172.39.0.32
    healthcheck:
      test: curl -s http://localhost:8686 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    # user: ${PUID}:${PGID} # linuxserver containers handle this with environment PUID, PGID
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./bazarr:/config
      - /mnt/nas:/mnt/nas
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6767:6767
    networks:
      homelabnetwork:
        ipv4_address: 172.39.0.33
    healthcheck:
      test: curl -s http://localhost:6767 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - deunhealth.restart.on.unhealthy=true
    restart: unless-stopped
